# .github/workflows/precommit.yml
name: Pre-commit checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run pre-commit (all files)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
